version: '3.8'

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: tpo
    volumes:
      - ./postgres-data:/var/lib/postgresql/data # persist data even if container shuts down
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql # init script, run after creating db automatically "docker-entrypoint-initdb.d"
    ports:
      - "5432:5432"
    networks:
      - backend

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: tpo
    volumes:
      - ./mongo-data:/data/db
    ports:
      - "27017:27017"
    networks:
      - backend

  api:
    container_name: api
    restart: unless-stopped
    build:
      context: api
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - backend
      - frontend
    depends_on:
      - postgres
      - mongo

  ui:
    container_name: ui
    restart: unless-stopped
    build:
      context: ui
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - frontend
    depends_on:
      - api
    

networks:
  backend:
  frontend: